### ISSUE TITLE
Setting up on AWS

### ISSUE THREAD

**Issue by kaustubhharapanahalli** [MausamGaurav/DockerDjangoReactProject#2]
Hello, 
I am trying to setup the project on AWS. I have a URL like https://test.demo 

I have passed this URL to the .env in the parent folder as `ENV_API_SERVER=test.demo`, but I am not able to access it over the browser. I have also added this to the DJANGO_ALLOWED_HOST as well. Could you please help me on how I can fix this?

Thanks

**Comment by MausamGaurav** [comment]
Hi, I would suggest performing a little bit of investigation. Firstly on AWS are you running that from a cloud compute instance? Please check your firewall settings. Also, you would need to check the security config of your AWS instance so that it allows both http and https. In your case it should be ENV_API_SERVER=https://test.demo. Further are you able to access the django admin page? If nothing works, I would suggest change the settings.js file to use your URL directly.

**Comment by kaustubhharapanahalli** [comment]
Thanks this fix worked. One more addition that I had to make was that in the docker-compose I had to set environment variable in the react docker to docker-compose.yml

```bash
environment:
    REACT_APP_API_SERVER: ${ENV_API_SERVER}
```

I have a continued question with respect to dockers with nginx.

Whatever value I enter on the frontend is getting saved but are not visible on the admin panel. Any idea what might be going wrong here? For example, I registered a user on the frontend, but it was not visible. Also, when I created a superuser on the backend, I am not able to login to the website from the frontend.
I removed the user registration in the entrypoint.sh
